language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="travis"

services:
  - postgresql

script:
  - python manage.py collectstatic
  - python manage.py test
# ...

# safelist
branches:
  only:
    - staging

# ...