# Generated by Django 2.0 on 2019-08-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('nutriments', models.TextField()),
                ('nutrient_levels', models.CharField(max_length=3000)),
                ('url', models.CharField(max_length=3000)),
                ('nutrition_score', models.CharField(max_length=10)),
                ('nutrition_100', models.CharField(max_length=5000)),
                ('image', models.CharField(max_length=3000)),
                ('category', models.ManyToManyField(related_name='cat_product', to='research.Category')),
            ],
            options={
                'verbose_name': 'Product',
            },
        ),
    ]
